name: testing worflow

on: push

jobs: 
    test-job:
        runs-on: ubuntu-latest

        steps: 
             - name: Hello disply
               run: echo "Hello kkfunda"

             - name: Disply the date
               run: date   
